### ISSUE TITLE
Simple Weather FC's when selecting Weather Graphs Before Going Through the Tutorial

### ISSUE THREAD

**Issue by moriel5** [Sparker0i/Weather#34] opened 2018-02-01 06:56 UTC
This won't be an issue most will notice, as it won't happen without a specific chain of actions, however I think it uncovers a second bug: The tutorial takes an extra second or two to appear.

Environment:
Device - Nexus 4
ROM - CRDroid
OS Version - 7.1.2

Steps to Reproduce:
1. Start a fresh instance of Simple Weather (by uninstalling and reinstalling, or by clearing data).
2. Enter Location name.
3. Immediately pulling the side menu, before the tutorial could start.
4. Select "Weather Graphs", and prevent the side menu from closing, or allowing the side menu from closing, and afterwards reopening the side menu.

In this scenario, Simple Weather only crashes in the side menu, after selecting "Weather Graphs", i.e. it is fine when viewing "Weather Graphs" or the settings.

**Comment by Sparker0i** [comment] 2018-02-01 07:38
This is a known bug

On 01-Feb-2018 12:26 PM, "moriel5" <notifications@github.com> wrote:

This won't be an issue most will notice, as it won't happen without a
specific chain of actions, however I think it uncovers a second bug: The
tutorial takes an extra second or two to appear.

Steps to reproduce:

   1. Start a fresh instance of Simple Weather (by uninstalling and
   reinstalling, or by clearing data).
   2. Enter Location name.
   3. Immediately pulling the side menu, before the tutorial could start.
   4. Select "Weather Graphs", and prevent the side menu from closing, or
   allowing the side menu from closing, and afterwards reopening the side menu.

In this scenario, Simple Weather only crashes in the side menu, after
selecting "Weather Graphs", i.e. it is fine when viewing "Weather Graphs"
or the settings.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Sparker0i/Weather/issues/34>, or mute the thread

**Comment by moriel5** [comment] 2018-02-01 09:29
Sorry about that, I see that I had forgotten to check other people's issues.

**Closed** 2018-08-31 20:38 UTC
Labels: cant-be-fixed-now
