### ISSUE TITLE
Simple Weather Randomly Unable to Load Data After Being Killed

### ISSUE THREAD

**Issue by moriel5** [Sparker0i/Weather#36] opened 2018-02-01 07:28 UTC
If Simple Weather is removed from the system memory, upon the first subsequent launch, Simple Weather may or may not be able to load it's data, with an endless loading pop up window showing if not.

Environment:
Device - Nexus 4
ROM - CRDroid
OS Version - 7.1.2

Prerequisites:
The app needs to be set up.
Optional - On ROMs that include this functionality, whether natively or by mods, the "Kill App" function needs to be mapped to a certain button.

Steps to Reproduce:
1. Force Close, a.k.a. kill, "Simple Weather".
2. Reopen "Simple Weather".

Current Workaround:
Kill "Simple Weather" again, and hope that the next time it launches all will be fine.

Logs will be taken after I return from work.

I had found this bug while reproducing the other bugs.

**Comment by Sparker0i** [comment] 2018-02-01 07:37
Is that still the same with simple weather 5.3?

**Comment by Sparker0i** [comment] 2018-02-01 08:22
Unable to reproduce that here

**Comment by moriel5** [comment] 2018-02-01 09:34
I'll run more tests at work, however it seems to resolved in 5.3.

**Comment by Sparker0i** [comment] 2018-08-31 20:42
Closing this for now. If the issue reappears, please feel free to reopen this issue. If you are not able to do so, comment here then I will open this again

**Closed** 2018-08-31 20:41 UTC
Labels: fixed

**Comment by moriel5** [comment] 2018-09-01 21:02
Sorry, I had a lot of things going on, and I had forgotten about this.
If this appears again though, I will comment on it.
