### ISSUE TITLE
Version 5.1 FC's Upon Entering City

### ISSUE THREAD

**Issue by moriel5** [Sparker0i/Weather#33] opened 2018-01-28 19:21 UTC
I had downloaded version 5.1 from XDA, and each time I had attempted to enter my city, first manually, and then automatically, however Simple Weather keeps on crashing on me.

This does not happen with version 4.1, which is the latest version on F-Droid.

I'll gladly send logs if needed, however I'd rather not make my location publicly available.

Update: I had manually downloaded version 4.1 using APKPure, and then I had set it up without any issues (I saw what you had meant by that the weather maps don't work, which is a shame, but oh well).

Afterwards, I went to update it to version 5.1, however XDA did not register the app as being installed (I presume that the XDA version has a different package name (I did not have time to check)), so I updated it using Yalp Store, and immediately upon opening, the app crashed, and would not open.

The same happened upon updating to version 5.0 with APKPure.

Update 2: I'm sorry I had forgotten to post my system details.
Device: Nexus 4
ROM: CRDroid, Android 7.1.2.
Kernel: SINAI-N4
UnifiedNLP: noGAPPS (I don't use the Play Services in any case)
Location Backends: Mozilla Location Service, Radiocells.org Unified Network Location Provider Backend
Address Lookup Backends: Nominatim
I also have the latest XPosed Framework installed, but no modules that have to do with location.

**Comment by Sparker0i** [comment] 2018-01-29 06:58
1. Which phone and which OS?
2. Detailed steps of reproduction
3. Logs please (may not help for me as you're using the release variant)

**Comment by moriel5** [comment] 2018-01-29 14:46
As I had edited in the OP:
Device: Nexus 4
ROM: CRDroid (Android 7.1.2)

Using UnifiedNLP without GAPPS (this is a noGAPPS setup)
Location Providers: Mozilla and Radiocells.org (which appears to be OpenBMap
Geolocation Providers: Nominatim

I have the latest version of XPosed Framework installed (not Magisk), however I have no modules that touch Simple Weather, or any location-related activiteus in general.


Steps to reproduce:

Manually:
1: Install version 5.1 of Simple Weather.
2: Enter location manually.
3: Simple Weather Force Closes

Automatically: 
1: Install version 5.1 of Simple Weather.
2: Press on automatic setup icon.
3: Simple Weather Force Closes.

I will run the required tests for installing 5.0, as well as installing 4.1 and then updating to 5.1 after work.

I had set MatLog to debug level (I am rooted), and filtered out the logs in accordance to Simple Weather's package name.

The log is short enough, that it contains running the app in both tests, killed in between, if there is any need.

Since I did not find any personal details (including location name), I had posted the logs on PasteBin.

Here are the logs: https://pastebin.com/jTadAWqh

**Comment by doryaspis** [comment] 2018-01-29 15:22
I'm experiencing the exact same behaviour as moriel5 but my setup is quite different: 

- Device: OnePlus 2
- ROM: OxygenOS version 3.6.1 
- Android version: 6.0.1 

I tried clearing the application's cache and data and also tried unistalling and reinstalling but the result is the same after you have specified your location. Toggling the Location permission seems to have no effect when you are entering the location info manually. 

Please note that I have tried the above with both v5 and v5.1 of your application.

**Comment by ithink314** [comment] 2018-01-29 21:58
Why is version 5 not building on F-droid?  https://f-droid.org/wiki/page/com.a5corp.weather

I experience similar crashes, with location, or entering city.
Nexus 6
Android 7.1.2
microG Lineage OS 14.1-20180126 
No gapps, on Google Fi (what is that Republic wireless app up to, I wonder :) )
GSM Location Service (on phone database)
Nominatim lookup backend

Log is attached including:
App Force Stop, clear cache, clear storage.
Install from Yalp
Start App, 
Start SatStat, get GPS fix, switch back to App
select location button, crash
Restart app
Enter city, crash

PS. Forecastie 1.6.1 is working OK, with City entered manually

[adb-logcat-5-exc.txt](https://github.com/Sparker0i/Weather/files/1675402/adb-logcat-5-exc.txt)
.

**Comment by Sparker0i** [comment] 2018-01-30 11:05
Hey there,

This has been fixed in 5.2

**Comment by moriel5** [comment] 2018-01-30 12:35
That's great to hear.
I'll be sure to test it out once I install it.

**Comment by doryaspis** [comment] 2018-01-31 16:14
Thank you very much for the quick fix! I can verify that the issue is no longer present on my device after updating to v5.2. I went ahead and added about five additional cities and experienced no problems. :)

**Comment by Sparker0i** [comment] 2018-01-31 18:42
Glad to know :)

**Closed by Sparker0i** 2018-01-31 18:42 UTC
